
export interface ColorItem {
    name: string;
    color: string;
    type: 'pure' | 'gradient';
    description?: string;
}

export interface ColorCategory {
    name: string;
    items: ColorItem[];
}

export const colorLibrary: ColorCategory[] = [
    {
        name: '精选渐变 (Top 50)',
        items: [
            { name: 'Warm Flame', color: 'linear-gradient(45deg, #ff9a9e 0%, #fad0c4 99%, #fad0c4 100%)', type: 'gradient', description: '温暖的火焰，柔和的粉橙色调' },
            { name: 'Night Fade', color: 'linear-gradient(to top, #a18cd1 0%, #fbc2eb 100%)', type: 'gradient', description: '夜幕降临，紫罗兰色的渐进' },
            { name: 'Spring Warmth', color: 'linear-gradient(to top, #fad0c4 0%, #ffd1ff 100%)', type: 'gradient', description: '春日的温暖，清新脱俗' },
            { name: 'Juicy Peach', color: 'linear-gradient(to right, #ffecd2 0%, #fcb69f 100%)', type: 'gradient', description: '水蜜桃般的甜香感' },
            { name: 'Young Passion', color: 'linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%)', type: 'gradient', description: '年轻的激情' },
            { name: 'Lady Lips', color: 'linear-gradient(to top, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)', type: 'gradient', description: '娇艳的唇色' },
            { name: 'Sunny Morning', color: 'linear-gradient(120deg, #f6d365 0%, #fda085 100%)', type: 'gradient' },
            { name: 'Rainy Ashville', color: 'linear-gradient(to top, #fdfcfb 0%, #e2ebf0 100%)', type: 'gradient' },
            { name: 'Frozen Dreams', color: 'linear-gradient(to top, #fdcbf1 0%, #fdcbf1 1%, #e6dee9 100%)', type: 'gradient' },
            { name: 'Winter Neva', color: 'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)', type: 'gradient' },
            { name: 'Dusty Grass', color: 'linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%)', type: 'gradient' },
            { name: 'Tempting Azure', color: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)', type: 'gradient' },
            { name: 'Heavy Rain', color: 'linear-gradient(to top, #cfd9df 0%, #e2ebf0 100%)', type: 'gradient' },
            { name: 'Amy Crisp', color: 'linear-gradient(120deg, #a6c0fe 0%, #f68084 100%)', type: 'gradient' },
            { name: 'Mean Fruit', color: 'linear-gradient(120deg, #fccb90 0%, #d57eeb 100%)', type: 'gradient' },
            { name: 'Deep Blue', color: 'linear-gradient(to right, #6a11cb 0%, #2575fc 100%)', type: 'gradient' },
            { name: 'Ripe Malinka', color: 'linear-gradient(120deg, #f093fb 0%, #f5576c 100%)', type: 'gradient' },
            { name: 'Cloudy Knoxville', color: 'linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)', type: 'gradient' },
            { name: 'Malibu Beach', color: 'linear-gradient(to right, #4facfe 0%, #00f2fe 100%)', type: 'gradient' },
            { name: 'New Retiro', color: 'linear-gradient(to top, #3b41c5 0%, #a981bb 49%, #ffc8a9 100%)', type: 'gradient' },
            { name: 'Fresh Milk', color: 'linear-gradient(to top, #feada6 0%, #f5efef 100%)', type: 'gradient' },
            { name: 'Snowy Mint', color: 'linear-gradient(to top, #e6e9f0 0%, #eef1f5 100%)', type: 'gradient' },
            { name: 'Everlasting Sky', color: 'linear-gradient(135deg, #fdfcfb 0%, #e2ebf0 100%)', type: 'gradient' },
            { name: 'Plum Plate', color: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', type: 'gradient' },
            { name: 'Premium Dark', color: 'linear-gradient(135deg, #434343 0%, #000000 100%)', type: 'gradient' },
            { name: 'Happy Fisher', color: 'linear-gradient(120deg, #89f7fe 0%, #66a6ff 100%)', type: 'gradient' },
            { name: 'Blessing', color: 'linear-gradient(to top, #fddb92 0%, #d1f2ff 100%)', type: 'gradient' },
            { name: 'Sharpeye', color: 'linear-gradient(to top, #330867 0%, #30cfd0 100%)', type: 'gradient' },
            { name: 'Stellar', color: 'linear-gradient(to right, #7474bf, #348ac7)', type: 'gradient' },
            { name: 'Under the Lake', color: 'linear-gradient(to right, #093028, #237a57)', type: 'gradient' },
            { name: 'Honey Dew', color: 'linear-gradient(to right, #43e97b 0%, #38f9d7 100%)', type: 'gradient' },
            { name: 'Morning Glow', color: 'linear-gradient(to right, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)', type: 'gradient' },
            { name: 'River City', color: 'linear-gradient(to top, #4481eb 0%, #04befe 100%)', type: 'gradient' },
            { name: 'Soft Grass', color: 'linear-gradient(to top, #c1dfc4 0%, #deecdd 100%)', type: 'gradient' },
            { name: 'Mars Party', color: 'linear-gradient(to top, #5f72bd 0%, #9b23ea 100%)', type: 'gradient' },
            { name: 'Eternal Constance', color: 'linear-gradient(to top, #09203f 0%, #537895 100%)', type: 'gradient' },
            { name: 'Japan Blush', color: 'linear-gradient(-20deg, #ddd6f3 0%, #faaca8 100%)', type: 'gradient' },
            { name: 'Smiling Rain', color: 'linear-gradient(-20deg, #dcb0ed 0%, #99c99c 100%)', type: 'gradient' },
            { name: 'Cloudy Apple', color: 'linear-gradient(to top, #f3e7e9 0%, #e3eeff 99%, #e3eeff 100%)', type: 'gradient' },
            { name: 'Big Mango', color: 'linear-gradient(to top, #f093fb 0%, #f5576c 100%)', type: 'gradient' },
            { name: 'Healthy Water', color: 'linear-gradient(120deg, #96deda 0%, #50c9c3 100%)', type: 'gradient' },
            { name: 'Amour Amour', color: 'linear-gradient(to top, #f77062 0%, #fe5196 100%)', type: 'gradient' },
            { name: 'Risky Concrete', color: 'linear-gradient(to top, #c471f5 0%, #fa71cd 100%)', type: 'gradient' },
            { name: 'Strong Bliss', color: 'linear-gradient(to right, #f78ca0 0%, #f9748f 19%, #fd868c 60%, #fe9a8b 100%)', type: 'gradient' },
            { name: 'Sweet Period', color: 'linear-gradient(to top, #3f51b1 0%, #5a55ae 13%, #7b5fac 25%, #8f67ab 38%, #a86aa4 50%, #cc6b8e 62%, #eb6b73 75%, #f3ac71 87%, #f3eb6d 100%)', type: 'gradient' }
        ]
    },
    {
        name: '中国传统色 (100+)',
        items: [
            { name: '朱砂', color: '#ff461f', type: 'pure', description: '中国红的代表，高贵热烈' },
            { name: '黛蓝', color: '#426666', type: 'pure', description: '深沉如黛，书卷气息' },
            { name: '琉璃', color: '#2a5caa', type: 'pure', description: '澄澈如琉璃，高雅宁静' },
            { name: '胭脂', color: '#9d2933', type: 'pure', description: '古典柔美，温婉动人' },
            { name: '竹青', color: '#789262', type: 'pure', description: '翠竹之色，生机勃勃' },
            { name: '琥珀', color: '#ca6924', type: 'pure', description: '晶莹通透，温暖醇厚' },
            { name: '艾翠', color: '#a1af9d', type: 'pure', description: '淡雅如艾，清爽自然' },
            { name: '藕荷', color: '#e4c6d0', type: 'pure', description: '藕花淡紫，温柔委婉' },
            { name: '玄青', color: '#3d3b4f', type: 'pure', description: '深沉肃穆，内敛深厚' },
            { name: '杏黄', color: '#ffa631', type: 'pure', description: '明亮欢快，如杏成熟' },
            { name: '秋香', color: '#d9b611', type: 'pure', description: '金秋之色，成熟内敛' },
            { name: '天青', color: '#1bd1a5', type: 'pure', description: '雨过天晴，清透淡雅' },
            { name: '苍色', color: '#7397ab', type: 'pure', description: '苍茫天色，宁静深远' },
            { name: '月白', color: '#d6ecf0', type: 'pure', description: '如月光皎洁，清新脱俗' },
            { name: '妃色', color: '#ed5736', type: 'pure', description: '杨妃之色，明艳照人' },
            { name: '桃红', color: '#f47983', type: 'pure' },
            { name: '海棠红', color: '#db5a6b', type: 'pure' },
            { name: '酡颜', color: '#f9906f', type: 'pure' },
            { name: '鹅黄', color: '#fff143', type: 'pure' },
            { name: '鸭蛋青', color: '#e0eee8', type: 'pure' },
            { name: '葱青', color: '#0eb83a', type: 'pure' },
            { name: '黛', color: '#4a4266', type: 'pure' },
            { name: '鸦青', color: '#424c50', type: 'pure' },
            { name: '黎', color: '#758a99', type: 'pure' },
            { name: '墨色', color: '#50616d', type: 'pure' },
            { name: '酡红', color: '#dc3023', type: 'pure' },
            { name: '牙白', color: '#fffbf0', type: 'pure' },
            { name: '绾', color: '#a98175', type: 'pure' },
            { name: '缃', color: '#f0c239', type: 'pure' },
            { name: '绀青', color: '#003371', type: 'pure' },
            { name: '绛紫', color: '#8c4356', type: 'pure' },
            { name: '栗色', color: '#60281e', type: 'pure' },
            { name: '驼色', color: '#a88462', type: 'pure' },
            { name: '藕色', color: '#edd1d8', type: 'pure' },
            { name: '松花', color: '#bce672', type: 'pure' },
            { name: '柳绿', color: '#afdd22', type: 'pure' },
            { name: '葱黄', color: '#a3d900', type: 'pure' },
            { name: '黛绿', color: '#424c50', type: 'pure' },
            { name: '葱蓝', color: '#a3d900', type: 'pure' },
            { name: '水红', color: '#f3d3e7', type: 'pure' },
            { name: '品红', color: '#f00056', type: 'pure' },
            { name: '宝蓝', color: '#4b5cc4', type: 'pure' },
            { name: '靛蓝', color: '#065279', type: 'pure' },
            { name: '翠绿', color: '#20a162', type: 'pure' },
            { name: '荷叶绿', color: '#1a6840', type: 'pure' },
            { name: '石青', color: '#163471', type: 'pure' },
            { name: '漆黑', color: '#161823', type: 'pure' },
            { name: '苍翠', color: '#519a73', type: 'pure' },
            { name: '茶色', color: '#b35c44', type: 'pure' },
            { name: '金茶', color: '#ed784a', type: 'pure' }
        ]
    },
    {
        name: '莫兰迪 & 莫奈',
        items: [
            { name: '莫兰迪粉', color: '#e2b3ad', type: 'pure' },
            { name: '静谧蓝', color: '#9dafc2', type: 'pure' },
            { name: '烟草绿', color: '#929c89', type: 'pure' },
            { name: '米驼色', color: '#c6b4a1', type: 'pure' },
            { name: '灰紫兰', color: '#b9a5ae', type: 'pure' },
            { name: '雾霾蓝', color: '#88a0b9', type: 'pure' },
            { name: '燕麦色', color: '#d9d0c7', type: 'pure' },
            { name: '松石绿', color: '#9bb0a5', type: 'pure' },
            { name: '陶土棕', color: '#9b7d6a', type: 'pure' },
            { name: '浅滩灰', color: '#c4c3c0', type: 'pure' },
            { name: '森林影', color: '#6b7a70', type: 'pure' },
            { name: '晨雾紫', color: '#aca5b0', type: 'pure' },
            { name: '古铜金', color: '#a69076', type: 'pure' },
            { name: '沙砾黄', color: '#dcc6ac', type: 'pure' },
            { name: '石楠红', color: '#b48a8a', type: 'pure' },
            { name: '雨后莫奈', color: '#8ca3ba', type: 'pure' },
            { name: '睡莲淡紫', color: '#c5b5cf', type: 'pure' },
            { name: '浮光绿', color: '#cbd4c1', type: 'pure' },
            { name: '池畔深绿', color: '#4a5744', type: 'pure' },
            { name: '晚霞粉', color: '#eab4b1', type: 'pure' }
        ]
    },
    {
        name: '品牌 & 科技',
        items: [
            { name: 'Tiffany Blue', color: '#0abab5', type: 'pure' },
            { name: 'Hermès Orange', color: '#f37021', type: 'pure' },
            { name: 'Coca-Cola Red', color: '#f40009', type: 'pure' },
            { name: 'Starbucks Green', color: '#00704a', type: 'pure' },
            { name: 'Facebook Blue', color: '#1877f2', type: 'pure' },
            { name: 'Google Blue', color: '#4285f4', type: 'pure' },
            { name: 'YouTube Red', color: '#ff0000', type: 'pure' },
            { name: 'Netfix Red', color: '#e50914', type: 'pure' },
            { name: 'Spotify Green', color: '#1db954', type: 'pure' },
            { name: 'Instagram 1', color: '#405de6', type: 'pure' },
            { name: 'Instagram 2', color: '#e1306c', type: 'pure' },
            { name: 'Twitter Blue', color: '#1da1f2', type: 'pure' },
            { name: 'Airbnb Pink', color: '#ff5a5f', type: 'pure' },
            { name: 'Slack Purple', color: '#4a154b', type: 'pure' },
            { name: 'Discord Blue', color: '#7289da', type: 'pure' },
            { name: 'Tiktok Black', color: '#010101', type: 'pure' },
            { name: 'Reddit Orange', color: '#ff4500', type: 'pure' },
            { name: 'Pinterest Red', color: '#bd081c', type: 'pure' }
        ]
    },
    {
        name: 'Material UI (200+)',
        items: [
            { name: 'Red 50', color: '#ffebee', type: 'pure' }, { name: 'Red 100', color: '#ffcdd2', type: 'pure' },
            { name: 'Red 200', color: '#ef9a9a', type: 'pure' }, { name: 'Red 300', color: '#e57373', type: 'pure' },
            { name: 'Red 400', color: '#ef5350', type: 'pure' }, { name: 'Red 500', color: '#f44336', type: 'pure' },
            { name: 'Red 600', color: '#e53935', type: 'pure' }, { name: 'Red 700', color: '#d32f2f', type: 'pure' },
            { name: 'Red 800', color: '#c62828', type: 'pure' }, { name: 'Red 900', color: '#b71c1c', type: 'pure' },
            { name: 'Blue 50', color: '#e3f2fd', type: 'pure' }, { name: 'Blue 100', color: '#bbdefb', type: 'pure' },
            { name: 'Blue 200', color: '#90caf9', type: 'pure' }, { name: 'Blue 300', color: '#64b5f6', type: 'pure' },
            { name: 'Blue 400', color: '#42a5f5', type: 'pure' }, { name: 'Blue 500', color: '#2196f3', type: 'pure' },
            { name: 'Blue 600', color: '#1e88e5', type: 'pure' }, { name: 'Blue 700', color: '#1976d2', type: 'pure' },
            { name: 'Blue 800', color: '#1565c0', type: 'pure' }, { name: 'Blue 900', color: '#0d47a1', type: 'pure' },
            { name: 'Green 50', color: '#e8f5e9', type: 'pure' }, { name: 'Green 100', color: '#c8e6c9', type: 'pure' },
            { name: 'Green 200', color: '#a5d6a7', type: 'pure' }, { name: 'Green 300', color: '#81c784', type: 'pure' },
            { name: 'Green 400', color: '#66bb6a', type: 'pure' }, { name: 'Green 500', color: '#4caf50', type: 'pure' },
            { name: 'Green 600', color: '#43a047', type: 'pure' }, { name: 'Green 700', color: '#388e3c', type: 'pure' },
            { name: 'Green 800', color: '#2e7d32', type: 'pure' }, { name: 'Green 900', color: '#1b5e20', type: 'pure' },
            { name: 'Orange 50', color: '#fff3e0', type: 'pure' }, { name: 'Orange 500', color: '#ff9800', type: 'pure' },
            { name: 'Purple 500', color: '#9c27b0', type: 'pure' }, { name: 'Amber 500', color: '#ffc107', type: 'pure' },
            { name: 'Cyan 500', color: '#00bcd4', type: 'pure' }, { name: 'Grey 500', color: '#9e9e9e', type: 'pure' }
        ]
    },
    {
        name: '经典 Pantone',
        items: [
            { name: 'Very Peri (2022)', color: '#6667AB', type: 'pure' },
            { name: 'Ultimate Gray (2021)', color: '#939597', type: 'pure' },
            { name: 'Illuminating (2021)', color: '#F5DF4D', type: 'pure' },
            { name: 'Classic Blue (2020)', color: '#0f4c81', type: 'pure' },
            { name: 'Living Coral (2019)', color: '#ff6f61', type: 'pure' },
            { name: 'Ultra Violet (2018)', color: '#663399', type: 'pure' },
            { name: 'Greenery (2017)', color: '#88b04b', type: 'pure' },
            { name: 'Rose Quartz (2016)', color: '#f7cac9', type: 'pure' },
            { name: 'Serenity (2016)', color: '#91a8d0', type: 'pure' },
            { name: 'Marsala (2015)', color: '#955251', type: 'pure' },
            { name: 'Radiant Orchid (2014)', color: '#b163a3', type: 'pure' },
            { name: 'Emerald (2013)', color: '#009473', type: 'pure' },
            { name: 'Tangerine Tango (2012)', color: '#dd4124', type: 'pure' }
        ]
    },
    {
        name: 'Flat UI 调色盘',
        items: [
            { name: 'Turquoise', color: '#1abc9c', type: 'pure' },
            { name: 'Emerland', color: '#2ecc71', type: 'pure' },
            { name: 'Peter River', color: '#3498db', type: 'pure' },
            { name: 'Amethyst', color: '#9b59b6', type: 'pure' },
            { name: 'Wet Asphalt', color: '#34495e', type: 'pure' },
            { name: 'Green Sea', color: '#16a085', type: 'pure' },
            { name: 'Nephritis', color: '#27ae60', type: 'pure' },
            { name: 'Belize Hole', color: '#2980b9', type: 'pure' },
            { name: 'Wisteria', color: '#8e44ad', type: 'pure' },
            { name: 'Midnight Blue', color: '#2c3e50', type: 'pure' },
            { name: 'Sun Flower', color: '#f1c40f', type: 'pure' },
            { name: 'Carrot', color: '#e67e22', type: 'pure' },
            { name: 'Alizarin', color: '#e74c3c', type: 'pure' },
            { name: 'Clouds', color: '#ecf0f1', type: 'pure' },
            { name: 'Concrete', color: '#95a5a6', type: 'pure' },
            { name: 'Orange', color: '#f39c12', type: 'pure' },
            { name: 'Pumpkin', color: '#d35400', type: 'pure' },
            { name: 'Pomegranate', color: '#c0392b', type: 'pure' },
            { name: 'Silver', color: '#bdc3c7', type: 'pure' },
            { name: 'Asbestos', color: '#7f8c8d', type: 'pure' }
        ]
    }
];
